import * as fs from "fs-extra"
import * as path from "path"
import * as prettier from "prettier"
import { IProjectInfo } from "./analyse-project-interface"
import { md5 } from "./md5"
import { IConfig } from "./project-config-interface"
import * as _ from "lodash"

interface IEntryInfo {
  pageImporter: string
  pageRoutes: string
  layoutImporter: string
  notFoundImporter: string
  notFoundRoute: string
  setEnv: string
  setCustomEnv: string
  storesImporter: string
  storesHelper: string
}

// Entry file content
const getEntryContent = (entryInfo: IEntryInfo, info: IProjectInfo, env: string) => `
  import { setEnvLocal, setEnvProd, setCustomEnv } from "pri"
  import * as React from "react"
  import * as ReactDOM from "react-dom"
  import Loadable from "react-loadable"
  import { Redirect, Route, Switch, Router } from "react-router-dom"
  import createBrowserHistory from 'history/createBrowserHistory'

  ${entryInfo.storesImporter}

  const customHistory = createBrowserHistory()

  ${entryInfo.setEnv}
  ${entryInfo.setCustomEnv}

  ${entryInfo.layoutImporter}
  ${entryInfo.notFoundImporter}
  ${entryInfo.pageImporter}

  class Root extends React.PureComponent<any, any> {
    public componentWillMount() {
      ${env === "local" ? `
        window.addEventListener("message", event => {
          const data = event.data
          switch(data.type) {
            case "changeRoute":
              customHistory.push(data.path) 
              break
            default:
          }
        }, false)
      `: ''}
    }

    public render() {
      return (
        ${info.stores.length > 0 ? "<Provider {...stores}>" : ""}
        <Router history={customHistory}>
          <Switch>
            ${entryInfo.pageRoutes}
            ${entryInfo.notFoundRoute}
          </Switch>
        </Router>
        ${info.stores.length > 0 ? "</Provider>" : ""}
      )
    }
  }

  ReactDOM.render(
    <Root />,
    document.getElementById("root")
  )
`

const getHelperContent = (entryInfo: IEntryInfo, info: IProjectInfo, env: string) => `
  /**
   * Do not edit this file.
   * This file is automatic generated to get type help.
   */
  
   ${entryInfo.storesHelper}
`

export async function createEntry(info: IProjectInfo, projectRootPath: string, env: string, config: IConfig) {
  const entryInfo: IEntryInfo = {
    pageImporter: "",
    pageRoutes: "",
    layoutImporter: "",
    notFoundImporter: "",
    notFoundRoute: "",
    setEnv: "",
    setCustomEnv: "",
    storesImporter: "",
    storesHelper: ""
  }

  // Set env
  switch (env) {
    case "local":
      entryInfo.setEnv = `setEnvLocal()`
      break
    case "prod":
      entryInfo.setEnv = `setEnvProd()`
      break
    default:
  }

  // Set custom env
  if (config.env) {
    entryInfo.setCustomEnv = `setCustomEnv(${JSON.stringify(config.env)})`
  }

  // Set routes
  info.routes.forEach(route => {
    const filePath = path.parse(route.filePath)
    const relativePageFilePath = path.relative(projectRootPath, filePath.dir + "/" + filePath.name)
    const componentName = relativePageFilePath.split("/").join("_")

    const pathInfo = path.parse(route.filePath)

    if (info.routes.length < 2) {
      // If only one page, don't need code splitting.
      if (info.stores.length === 0) {
        entryInfo.pageImporter += `
          import ${componentName} from "${path.join(pathInfo.dir, pathInfo.name)}"
        `
      } else {
        entryInfo.pageImporter += `
          import ${componentName}Temp from "${path.join(pathInfo.dir, pathInfo.name)}"
          ${componentName} = Connect()(${componentName}Temp)
        `
      }
    } else {
      const importCode = info.stores.length === 0 ?
        `import("${path.join(pathInfo.dir, pathInfo.name)}")` :
        `import("${path.join(pathInfo.dir, pathInfo.name)}").then(res => Connect()(res.default))  `

      entryInfo.pageImporter += `
        const ${componentName} = Loadable({
          loader: () => ${importCode},
          loading: () => null
        })\n
      `
    }

    const routeComponent = info.layout ? "LayoutRoute" : "Route"

    entryInfo.pageRoutes += `
      <${routeComponent} exact path="${route.path}" component={${componentName}} />\n
    `
  })

  // Set stores
  const safeName = (str: string) => _.upperFirst(_.camelCase(str))
  if (info.stores.length > 0) {
    entryInfo.storesImporter += `import { useStrict } from "dob"\n`
    entryInfo.storesImporter += `import { Connect, Provider } from "dob-react"\n`
    entryInfo.storesImporter += `useStrict()\n`
    entryInfo.storesImporter += `import { stores } from "../src/helper"\n`
    entryInfo.storesHelper += `import { combineStores } from "dob"\n`
    entryInfo.storesHelper += info.stores
      .map(eachStore => {
        const filePath = path.parse(eachStore.filePath)
        const importAbsolutePath = path.join(filePath.dir, filePath.name)
        const importRelativePath = path.relative(path.join(projectRootPath, "src"), importAbsolutePath)
        return `import { ${safeName(eachStore.name)}Action, ${safeName(eachStore.name)}Store } from "./${importRelativePath}"`
      })
      .join("\n")
    entryInfo.storesHelper += `
      \nconst stores = combineStores({${info.stores.map(eachStore => {
        return `${safeName(eachStore.name)}Action, ${safeName(eachStore.name)}Store`
      }).join(',')}})
      
      export { stores }
    `
  }

  // Set layout
  if (info.layout) {
    const layoutPath = path.parse(info.layout.filePath)
    entryInfo.layoutImporter = `
      import LayoutComponent from "${path.join(layoutPath.dir, layoutPath.name)}"

      const LayoutRoute = ({ component: Component, ...rest }) => {
        return (
          <Route {...rest} render={matchProps => (
            <LayoutComponent>
              <Component {...matchProps} />
            </LayoutComponent>
          )} />
        )
      };\n
    `
  }

  // Set not found
  if (info.notFound) {
    const notFoundPath = path.parse(info.notFound.filePath)
    entryInfo.notFoundImporter = `import NotFoundComponent from "${path.join(notFoundPath.dir, notFoundPath.name)}"`
    entryInfo.notFoundRoute = `
      <Route component={NotFoundComponent} />
    `
  }

  // Create entry tsx file
  const entryPath = path.join(projectRootPath, ".temp/entry.tsx")
  fs.outputFileSync(entryPath, prettier.format(getEntryContent(entryInfo, info, env), {
    semi: false,
    parser: "typescript"
  }))

  // If has stores, create helper.ts
  const helperPath = path.join(projectRootPath, "src/helper.ts")
  if (info.stores.length > 0) {
    fs.outputFileSync(helperPath, prettier.format(getHelperContent(entryInfo, info, env), {
      semi: false,
      parser: "typescript"
    }))
  } else {
    fs.removeSync(helperPath)
  }

  return entryPath
}
